### ISSUE TITLE
Automatically shut down deepracer instances that have been running for more than 12 hours

### ISSUE THREAD

**Issue by tylerwooten** [EsaLaine/deepracer-templates#10]
Create a scheduled function that checks if an instance that was created with cloudformation has been running for > 12 hours and send an interruption notice to the instance and terminate.

Console limits models to training for 24 hours, but we can be more conservative.

**Comment by pgdad** [comment]
Please make a 'safe termination' shell script example, I will incorporate that once available.

**Comment by tylerwooten** [comment]
made safe_termination.sh in /home/ubuntu/bin/ and this is all we need:

#!/bin/bash
dr-stop-training
dr-upload-model -bf

**Comment by pgdad** [comment]
This is really a subset of https://github.com/EsaLaine/deepracer-templates/issues/11, will implement as part of issues/11.
