### ISSUE TITLE
Detect if user is running the latest version when running "Create" script

### ISSUE THREAD

**Issue by MaikelGit** [EsaLaine/deepracer-templates#20]
we can make this mandatory or just a warning, but I think it would be good to make the user aware when using the tool that there is a newer version available

**Comment by pgdad** [comment]
Latest version of what? Cloudformation templates, or docker containers?

**Comment by MaikelGit** [comment]
I was thinking that when the users run for example the
create-spot-instance.sh the script could check if the cloned local version
is the latest available in the github repo.

I know the users might have changed the content of the custom files folder
but the time the users run that script, so wanted to discuss with you and
the team the best approach to confirm the are running the latest main
branch version. It does not need to be mandatory, but at least to alert the
users the might not have the latest enhancements and fixes.

Does it makes sense?

Thanks and regards,
Miguel

**Comment by pgdad** [comment]
We have to be able to make some assumptions on 'what the users need to know'. I would vote that basic git operations fall into the 'assume the user knows, or has the means to learn, after all we are using github'.
Additionally, there are many valid reasons why one would want to use an older (or different branch) version of the scripts.

**Comment by MaikelGit** [comment]
i am ok with any approach, I just thought we might want the user be aware there is a new release available (not mandatory) when they run the commands, as they might not be checking for a new release at all times.

**Comment by pgdad** [comment]
no changes at this time
