### ISSUE TITLE
Create custom files validation script that runs before files are uploaded to s3

### ISSUE THREAD

**Issue by tylerwooten** [EsaLaine/deepracer-templates#6]
In order to catch errors before provisioning the instance, we can create a validation script that ensures the custom files don't have any syntax errors and that the tracks exist, race type exists, etc.

**Comment by MaikelGit** [comment]
other things we can validate to minimiza the training errors:
- the pre-trained model prefix exists on the S3 bucket
- the new model prefix does not exist or request user confirmation to overwrite, as today the dr-start-training command does not have -w to overwrite and will fail
- based on the instance type and values on the hyperparamenters, system.env and run.env validate the DR_TRAIN_ROUND_ROBIN_ADVANCE_DIST is properly calculated or suggest a new value if the DR_TRAIN_CHANGE_START_POSITION is True
